### ISSUE TITLE
[Question] How do I utilize the role that a codebuild runner is using?

### ISSUE THREAD

**Issue by laxgoalie392** [CloudSnorkel/cdk-github-runners#113]
I'm using a codebuild runner and trying to run an action that relies on aws credentials.

i've tried using the following step in my workflow:

```yaml
- name: Test
  run: aws sts get-caller-identity
```

but i end up getting the following error:

```
Unable to locate credentials. You can configure credentials by running "aws configure".
```

I also tried using the aws configure credentials action but am hitting basically the same error
```yaml
- name: AWS Secure Access
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-region: us-east-1
```

My first impression was that I would be able to inherit the role that the codebuild runner was using
