### ISSUE TITLE
ECR login does not work with inherited role

### ISSUE THREAD

**Issue by laxgoalie392** [CloudSnorkel/cdk-github-runners#117]
Related to #113.

I haven't looked into this one yet but i just want to jot it down.

I applied the fix in #114. Initial use of the inherited worked to get secrets but i and ran into the following in a later step:

```Error saving credentials: open /home/runner/.docker/config.json2271103188: permission denied```

i'm trying to use this action:

```yaml
- name: Login to Amazon ECR
  uses: aws-actions/amazon-ecr-login@v1
  with:
    registries: "****"
```

feels like a file system issue
