### ISSUE TITLE
Default labels not working

### ISSUE THREAD

**Issue by garysassano** [CloudSnorkel/cdk-github-runners#635]
I followed the README instructions up to point 8.

![image](https://github.com/user-attachments/assets/4f029591-2d49-43d5-acb3-badc62ae3f68)

But there's no runner with the `[self-hosted, linux, codebuild]` labels.

![image](https://github.com/user-attachments/assets/da109728-9ca8-4cb4-bc70-abb35b547f72)

**Comment by garysassano** [comment]
I confirm that the following custom label works perfectly on the other hand.

![image](https://github.com/user-attachments/assets/4b10b3db-2851-43d9-9445-f15f6c6b643b)

**Comment by kichik** [comment]
Can you include the workflow and the code you originally used?

If you used the defaults, it might be that the documentation is wrong and you need to remove the `linux` label from the workflow.

**Comment by garysassano** [comment]
>Can you include the workflow and the code you originally used?

#### test.yml

```yml
name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, linux, codebuild]
    steps:
      - run: echo "Hello World!"
```
